import { config } from "dotenv";

config();

const {
  PORT,
  NODE_ENV,
  FRONTEND_DOMAIN,
  DASHBOARD_DOMAIN,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ACCESS_TOEKN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY,
  FORGET_PASSWORD_TOKEN_SECRET,
  MONGO_URL,

  SMTP_HOST,
  SMTP_PORT,
  MAIL_USER,
  MAIL_PASSWORD,
  GOOGLE_PROJECT_ID,
  GOOGLE_APPLICATION_CREDENTIALS,
  GOOGLE_API_KEY,
} = process.env;

const Config = {
  PORT,
  NODE_ENV,
  FRONTEND_DOMAIN,
  DASHBOARD_DOMAIN,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  ACCESS_TOEKN_SECRET_KEY,
  REFRESH_TOKEN_SECRET_KEY,
  FORGET_PASSWORD_TOKEN_SECRET,
  MONGO_URL,

  SMTP_HOST,
  SMTP_PORT,
  MAIL_USER,
  MAIL_PASSWORD,
  GOOGLE_PROJECT_ID,
  GOOGLE_APPLICATION_CREDENTIALS,
  GOOGLE_API_KEY,
  SUPPORTED_LANGUAGES: ["de", "fr", "es", "it", "hi", "zh"],
};

export default Config;
